# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: THE BURGE
email: the-burge@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Jim Burger is an experienced software developer who has been developing .NET based solutions for business since 2004, and has led multiple teams to deliver high quality software for businesses and government around Australia. He is a father of three, husband, musician and avid gamer, who believes that fun is a measure of success.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.theburge.co" # the base hostname & protocol for your site
twitter_username: burgomg
github_username:  jburger

# Build settings
markdown: kramdown
